<a href="https://www.kaggle.com/code/zlimshady/missing-immigrant-globally-data?scriptVersionId=124322445" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/missing-migrants-globally-from-2022-10-21-to-date/missingmigrants-global-2022-10-21t22-36-040800.xlsx

## **Missing Migrants Project**

Missing Migrants Project draws on a range of sources to track deaths of migrants along migratory routes across the globe. Data from this project are published in the report “Fatal Journeys: Tracking Lives Lost during Migration,” which provides the most comprehensive global tally of migrant fatalities for 2014, and estimates deaths over the past 15 years.

In [2]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:

immigrant_df = pd.read_excel('/kaggle/input/missing-migrants-globally-from-2022-10-21-to-date/missingmigrants-global-2022-10-21t22-36-040800.xlsx')

## Data Cleaning

In [4]:
immigrant_df

,Main ID,Incident ID,Region,Incident Date,Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,...,Number of Males,Number of Children,Cause of Death,Location of death,Information Source,Coordinates,Migrantion route,URL,UNSD Geographical Grouping,Source Quality
0,2022.MMP00001,2022.MMP00001,Mediterranean,"Sun, 01/02/2022 - 12:00",2022,January,1.0,NaN,1,NaN,...,NaN,1.0,Drowning,"Retrieved from waters one mile off Aftis, El A...",DPC Jijel,"36.71614878, 5.552716421",Western Mediterranean,https://archive.vn/Fm04u,Uncategorized,5
1,2022.MMP00002,2022.MMP00002,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,8.0,11,3.0,...,NaN,NaN,Drowning,"Off Plage Ben Zouit, Kerkera, Skikda, Algeria ...","DPC Skkikda, Echorouk Online, Akher Saa","36.97321267, 6.599006494",Central Mediterranean,"https://archive.vn/ExMIR, https://archive.vn/Y...",Uncategorized,5
2,2022.MMP00003,2022.MMP00003,Southern Africa,"Mon, 01/03/2022 - 12:00",2022,January,3.0,3.0,6,2.0,...,6.0,NaN,Drowning,"Limpopo river, near Maroi, Limpopo province, S...",IOM Zimbabwe,"-22.177258, 29.862273",NaN,NaN,Uncategorized,5
3,2022.MMP00004,2022.MMP00004,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,14.0,17,16.0,...,NaN,1.0,Drowning,"Off the coast of Cabo de Gata, Almería, Spain","IOM Spain, El País, ABC","36.523849, -2.117221",Western Mediterranean,"https://archive.ph/y0PiC, https://archive.ph/f...",Uncategorized,4
4,2022.MMP00005,2022.MMP00005,Southern Asia,"Sat, 01/01/2022 - 12:00",2022,January,1.0,NaN,1,2.0,...,NaN,NaN,Harsh environmental conditions / lack of adequ...,"Remains found near the village of Belasur, Kho...",Twitter@tcvanvaliligi (Türkiye-Van Governor's ...,"38.566055, 44.344085",Iran to Türkiye,"https://archive.ph/MjeLH, https://archive.ph/b...",Southern Asia,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1235,2022.MMP1209,2022.MMP1209,Eastern Africa,"Tue, 10/18/2022 - 12:00",2022,October,25.0,NaN,25,NaN,...,25.0,NaN,Mixed or unknown,Golong'ondo area in Mtangatanga Forest Reserve...,"AFP, Anadolu Agency","-11.8437, 33.7068",NaN,"https://archive.ph/OQQcY, https://archive.ph/8...",Eastern Africa,3
1236,2022.MMP1210,2022.MMP1210,Central America,"Tue, 10/18/2022 - 12:00",2022,October,3.0,NaN,3,5.0,...,3.0,NaN,Vehicle accident / death linked to hazardous t...,"Highway in Suchiate, Chiapas, Mexico","AP, El Diario, La Razon","14.64392901, -92.24443008",NaN,"https://archive.ph/4kayN, https://archive.ph/A...",Central America,3
1237,2022.MMP1211,2022.MMP1211,Central America,"Wed, 10/19/2022 - 12:00",2022,October,1.0,NaN,1,NaN,...,1.0,NaN,Vehicle accident / death linked to hazardous t...,"Train tracks in Morelos, Guadalajara, Jalisco,...","Informador, Notisistema","20.6571776, -103.3553036",NaN,"https://archive.ph/iCHD9, https://archive.ph/F...",Central America,3
1238,2022.MMP1212,2022.MMP1212,Northern Africa,"Wed, 10/12/2022 - 12:00",2022,October,NaN,22.0,22,30.0,...,NaN,NaN,Drowning,"Off the coast of Tan-Tan, Morocco","Halena Maleno, Hespress","28.74565827, -11.2988",Western Africa / Atlantic route to the Canary ...,"https://archive.ph/13c5g, https://archive.ph/c...",Uncategorized,4
1239,2022.MMP1213,2022.MMP1213,Mediterranean,"Thu, 10/13/2022 - 12:00",2022,October,2.0,5.0,7,8.0,...,NaN,2.0,Drowning,"Off the coast of Skikda, Algeria (East)","Al Quds, Skikda News Facebook Page","0, 0",Central Mediterranean,"https://archive.ph/, https://www.facebook.com/...",NaN,3

In [5]:
#We can view some basic information about the data frame using the .info method.

immigrant_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1240 entries, 0 to 1239
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Main ID                              1240 non-null   object
 1   Incident ID                          1240 non-null   object
 2   Region                               1240 non-null   object
 3   Incident Date                        1240 non-null   object
 4   Year                                 1240 non-null   int64
 5   Reported Month                       1240 non-null   object
 6   Number Dead                          1140 non-null   float64
 7   Minimum Estimated Number of Missing  177 non-null    float64
 8   Total Number of Dead and Missing     1240 non-null   int64
 9   Number of Survivors                  287 non-null    float64
 10  Number of Females                    219 non-null    float64
 11  Number of Males                      763 non-null    float64
 12  Number of Children                   144 non-null    float64
 13  Cause of Death                       1240 non-null   object
 14  Location of death                    1240 non-null   object
 15  Information Source                   1240 non-null   object
 16  Coordinates                          1240 non-null   object
 17  Migrantion route                     1044 non-null   object
 18  URL                                  840 non-null    object
 19  UNSD Geographical Grouping           1239 non-null   object
 20  Source Quality                       1240 non-null   int64
dtypes: float64(6), int64(3), object(12)
memory usage: 203.6+ KB

In [6]:
# It appears that each column contains values of a specific data type. You can view statistical information for numerical columns (mean, standard deviation, minimum/maximum values, and the number of non-empty values) using the .describe method.

immigrant_df.describe()

,Year,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Source Quality
count,1240.0,1140.000000,177.000000,1240.000000,287.000000,219.000000,763.000000,144.000000,1240.000000
mean,2022.0,1.849123,10.254237,3.163710,33.515679,1.721461,1.449541,1.701389,3.633065
std,0.0,3.847174,13.200714,7.500969,73.218365,2.163086,2.016600,1.434246,1.256475
min,2022.0,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000
25%,2022.0,1.000000,2.000000,1.000000,4.500000,1.000000,1.000000,1.000000,3.000000
50%,2022.0,1.000000,5.000000,1.000000,12.000000,1.000000,1.000000,1.000000,4.000000
75%,2022.0,1.000000,14.000000,2.000000,34.500000,1.000000,1.000000,2.000000,5.000000
max,2022.0,102.000000,96.000000,122.000000,674.000000,16.000000,27.000000,9.000000,5.000000

In [7]:
#The columns property contains the list of columns within the data frame.

immigrant_df.columns

Index(['Main ID', 'Incident ID', 'Region', 'Incident Date', 'Year',
       'Reported Month', 'Number Dead', 'Minimum Estimated Number of Missing',
       'Total Number of Dead and Missing', 'Number of Survivors',
       'Number of Females', 'Number of Males', 'Number of Children',
       'Cause of Death', 'Location of death', 'Information Source',
       'Coordinates', 'Migrantion route', 'URL', 'UNSD Geographical Grouping',
       'Source Quality'],
      dtype='object')

We can use the .head and .tail methods to view the first or last few rows of data.

In [8]:
immigrant_df.head(5)

,Main ID,Incident ID,Region,Incident Date,Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,...,Number of Males,Number of Children,Cause of Death,Location of death,Information Source,Coordinates,Migrantion route,URL,UNSD Geographical Grouping,Source Quality
0,2022.MMP00001,2022.MMP00001,Mediterranean,"Sun, 01/02/2022 - 12:00",2022,January,1.0,NaN,1,NaN,...,NaN,1.0,Drowning,"Retrieved from waters one mile off Aftis, El A...",DPC Jijel,"36.71614878, 5.552716421",Western Mediterranean,https://archive.vn/Fm04u,Uncategorized,5
1,2022.MMP00002,2022.MMP00002,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,8.0,11,3.0,...,NaN,NaN,Drowning,"Off Plage Ben Zouit, Kerkera, Skikda, Algeria ...","DPC Skkikda, Echorouk Online, Akher Saa","36.97321267, 6.599006494",Central Mediterranean,"https://archive.vn/ExMIR, https://archive.vn/Y...",Uncategorized,5
2,2022.MMP00003,2022.MMP00003,Southern Africa,"Mon, 01/03/2022 - 12:00",2022,January,3.0,3.0,6,2.0,...,6.0,NaN,Drowning,"Limpopo river, near Maroi, Limpopo province, S...",IOM Zimbabwe,"-22.177258, 29.862273",NaN,NaN,Uncategorized,5
3,2022.MMP00004,2022.MMP00004,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,14.0,17,16.0,...,NaN,1.0,Drowning,"Off the coast of Cabo de Gata, Almería, Spain","IOM Spain, El País, ABC","36.523849, -2.117221",Western Mediterranean,"https://archive.ph/y0PiC, https://archive.ph/f...",Uncategorized,4
4,2022.MMP00005,2022.MMP00005,Southern Asia,"Sat, 01/01/2022 - 12:00",2022,January,1.0,NaN,1,2.0,...,NaN,NaN,Harsh environmental conditions / lack of adequ...,"Remains found near the village of Belasur, Kho...",Twitter@tcvanvaliligi (Türkiye-Van Governor's ...,"38.566055, 44.344085",Iran to Türkiye,"https://archive.ph/MjeLH, https://archive.ph/b...",Southern Asia,5

In [9]:
immigrant_df.tail(5)

,Main ID,Incident ID,Region,Incident Date,Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,...,Number of Males,Number of Children,Cause of Death,Location of death,Information Source,Coordinates,Migrantion route,URL,UNSD Geographical Grouping,Source Quality
1235,2022.MMP1209,2022.MMP1209,Eastern Africa,"Tue, 10/18/2022 - 12:00",2022,October,25.0,NaN,25,NaN,...,25.0,NaN,Mixed or unknown,Golong'ondo area in Mtangatanga Forest Reserve...,"AFP, Anadolu Agency","-11.8437, 33.7068",NaN,"https://archive.ph/OQQcY, https://archive.ph/8...",Eastern Africa,3
1236,2022.MMP1210,2022.MMP1210,Central America,"Tue, 10/18/2022 - 12:00",2022,October,3.0,NaN,3,5.0,...,3.0,NaN,Vehicle accident / death linked to hazardous t...,"Highway in Suchiate, Chiapas, Mexico","AP, El Diario, La Razon","14.64392901, -92.24443008",NaN,"https://archive.ph/4kayN, https://archive.ph/A...",Central America,3
1237,2022.MMP1211,2022.MMP1211,Central America,"Wed, 10/19/2022 - 12:00",2022,October,1.0,NaN,1,NaN,...,1.0,NaN,Vehicle accident / death linked to hazardous t...,"Train tracks in Morelos, Guadalajara, Jalisco,...","Informador, Notisistema","20.6571776, -103.3553036",NaN,"https://archive.ph/iCHD9, https://archive.ph/F...",Central America,3
1238,2022.MMP1212,2022.MMP1212,Northern Africa,"Wed, 10/12/2022 - 12:00",2022,October,NaN,22.0,22,30.0,...,NaN,NaN,Drowning,"Off the coast of Tan-Tan, Morocco","Halena Maleno, Hespress","28.74565827, -11.2988",Western Africa / Atlantic route to the Canary ...,"https://archive.ph/13c5g, https://archive.ph/c...",Uncategorized,4
1239,2022.MMP1213,2022.MMP1213,Mediterranean,"Thu, 10/13/2022 - 12:00",2022,October,2.0,5.0,7,8.0,...,NaN,2.0,Drowning,"Off the coast of Skikda, Algeria (East)","Al Quds, Skikda News Facebook Page","0, 0",Central Mediterranean,"https://archive.ph/, https://www.facebook.com/...",NaN,3

In [10]:
# Dropping all rows that are not useful in the analysis 

immigrant_df.drop(['Main ID','Incident ID','Location of death','Information Source','Coordinates','Migrantion route','URL','UNSD Geographical Grouping','Source Quality'], axis = 1, inplace = True)

In [11]:
immigrant_df

,Region,Incident Date,Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death
0,Mediterranean,"Sun, 01/02/2022 - 12:00",2022,January,1.0,NaN,1,NaN,NaN,NaN,1.0,Drowning
1,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,8.0,11,3.0,NaN,NaN,NaN,Drowning
2,Southern Africa,"Mon, 01/03/2022 - 12:00",2022,January,3.0,3.0,6,2.0,NaN,6.0,NaN,Drowning
3,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,14.0,17,16.0,1.0,NaN,1.0,Drowning
4,Southern Asia,"Sat, 01/01/2022 - 12:00",2022,January,1.0,NaN,1,2.0,1.0,NaN,NaN,Harsh environmental conditions / lack of adequ...
...,...,...,...,...,...,...,...,...,...,...,...,...
1235,Eastern Africa,"Tue, 10/18/2022 - 12:00",2022,October,25.0,NaN,25,NaN,NaN,25.0,NaN,Mixed or unknown
1236,Central America,"Tue, 10/18/2022 - 12:00",2022,October,3.0,NaN,3,5.0,NaN,3.0,NaN,Vehicle accident / death linked to hazardous t...
1237,Central America,"Wed, 10/19/2022 - 12:00",2022,October,1.0,NaN,1,NaN,NaN,1.0,NaN,Vehicle accident / death linked to hazardous t...
1238,Northern Africa,"Wed, 10/12/2022 - 12:00",2022,October,NaN,22.0,22,30.0,NaN,NaN,NaN,Drowning
1239,Mediterranean,"Thu, 10/13/2022 - 12:00",2022,October,2.0,5.0,7,8.0,NaN,NaN,2.0,Drowning

In [12]:
# Checks for null Values, Returns Boolean Array

pd.isnull(immigrant_df)

,Region,Incident Date,Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death
0,False,False,False,False,False,True,False,True,True,True,False,False
1,False,False,False,False,False,False,False,False,True,True,True,False
2,False,False,False,False,False,False,False,False,True,False,True,False
3,False,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,True,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1235,False,False,False,False,False,True,False,True,True,False,True,False
1236,False,False,False,False,False,True,False,False,True,False,True,False
1237,False,False,False,False,False,True,False,True,True,False,True,False
1238,False,False,False,False,True,False,False,False,True,True,True,False
1239,False,False,False,False,False,False,False,False,True,True,False,False

In [13]:
# Replaces all null values with 0

immigrant_df = immigrant_df.fillna(0)
immigrant_df

,Region,Incident Date,Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death
0,Mediterranean,"Sun, 01/02/2022 - 12:00",2022,January,1.0,0.0,1,0.0,0.0,0.0,1.0,Drowning
1,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,8.0,11,3.0,0.0,0.0,0.0,Drowning
2,Southern Africa,"Mon, 01/03/2022 - 12:00",2022,January,3.0,3.0,6,2.0,0.0,6.0,0.0,Drowning
3,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,14.0,17,16.0,1.0,0.0,1.0,Drowning
4,Southern Asia,"Sat, 01/01/2022 - 12:00",2022,January,1.0,0.0,1,2.0,1.0,0.0,0.0,Harsh environmental conditions / lack of adequ...
...,...,...,...,...,...,...,...,...,...,...,...,...
1235,Eastern Africa,"Tue, 10/18/2022 - 12:00",2022,October,25.0,0.0,25,0.0,0.0,25.0,0.0,Mixed or unknown
1236,Central America,"Tue, 10/18/2022 - 12:00",2022,October,3.0,0.0,3,5.0,0.0,3.0,0.0,Vehicle accident / death linked to hazardous t...
1237,Central America,"Wed, 10/19/2022 - 12:00",2022,October,1.0,0.0,1,0.0,0.0,1.0,0.0,Vehicle accident / death linked to hazardous t...
1238,Northern Africa,"Wed, 10/12/2022 - 12:00",2022,October,0.0,22.0,22,30.0,0.0,0.0,0.0,Drowning
1239,Mediterranean,"Thu, 10/13/2022 - 12:00",2022,October,2.0,5.0,7,8.0,0.0,0.0,2.0,Drowning

In [14]:
# method of retrieve a random sample of rows from the data frame.

immigrant_df.sample(10)

,Region,Incident Date,Year,Reported Month,Number Dead,Minimum Estimated Number of Missing,Total Number of Dead and Missing,Number of Survivors,Number of Females,Number of Males,Number of Children,Cause of Death
454,Europe,"Wed, 05/11/2022 - 12:00",2022,May,1.0,0.0,1,0.0,0.0,0.0,0.0,Violence
338,North America,"Sat, 02/19/2022 - 12:00",2022,February,1.0,0.0,1,0.0,0.0,1.0,0.0,Violence
269,Southern Asia,"Sun, 01/30/2022 - 12:00",2022,January,1.0,0.0,1,0.0,0.0,1.0,0.0,Sickness / lack of access to adequate healthcare
308,North America,"Mon, 03/21/2022 - 12:00",2022,March,1.0,0.0,1,0.0,0.0,1.0,0.0,Harsh environmental conditions / lack of adequ...
578,Central America,"Mon, 05/16/2022 - 12:00",2022,May,1.0,0.0,1,0.0,0.0,1.0,0.0,Harsh environmental conditions / lack of adequ...
353,Caribbean,"Thu, 04/07/2022 - 12:00",2022,April,4.0,0.0,4,0.0,0.0,0.0,0.0,Drowning
231,Southern Asia,"Tue, 01/04/2022 - 12:00",2022,January,1.0,0.0,1,0.0,0.0,1.0,0.0,Vehicle accident / death linked to hazardous t...
339,North America,"Thu, 03/31/2022 - 12:00",2022,March,1.0,0.0,1,7.0,0.0,1.0,0.0,Drowning
483,Southern Asia,"Sun, 04/03/2022 - 12:00",2022,April,1.0,0.0,1,0.0,0.0,1.0,0.0,Sickness / lack of access to adequate healthcare
384,Central America,"Fri, 04/15/2022 - 12:00",2022,April,1.0,0.0,1,0.0,0.0,1.0,0.0,Harsh environmental conditions / lack of adequ...

In [15]:
#renaming the columns

immigrant_df = immigrant_df.rename(columns={'Incident Date': 'Incident_Date', 'Reported Month' : 'Reported_Month', 'Number Dead' : 'Number_Dead', 'Minimum Estimated Number of Missing' : 'Minimum_Estimated_Number_of_Missing', 'Total Number of Dead and Missing' : 'Total Number_of_Dead_and_Missing', 'Number of Survivors' : 'Number_of_Survivors', 'Number of Females' : 'Number_of_Females', 'Number of Males' : 'Number_of_Males', 'Number of Children' : 'Number_of_Children', 'Cause of Death' : 'Cause_of_Death' })

In [16]:
immigrant_df

,Region,Incident_Date,Year,Reported_Month,Number_Dead,Minimum_Estimated_Number_of_Missing,Total Number_of_Dead_and_Missing,Number_of_Survivors,Number_of_Females,Number_of_Males,Number_of_Children,Cause_of_Death
0,Mediterranean,"Sun, 01/02/2022 - 12:00",2022,January,1.0,0.0,1,0.0,0.0,0.0,1.0,Drowning
1,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,8.0,11,3.0,0.0,0.0,0.0,Drowning
2,Southern Africa,"Mon, 01/03/2022 - 12:00",2022,January,3.0,3.0,6,2.0,0.0,6.0,0.0,Drowning
3,Mediterranean,"Mon, 01/03/2022 - 12:00",2022,January,3.0,14.0,17,16.0,1.0,0.0,1.0,Drowning
4,Southern Asia,"Sat, 01/01/2022 - 12:00",2022,January,1.0,0.0,1,2.0,1.0,0.0,0.0,Harsh environmental conditions / lack of adequ...
...,...,...,...,...,...,...,...,...,...,...,...,...
1235,Eastern Africa,"Tue, 10/18/2022 - 12:00",2022,October,25.0,0.0,25,0.0,0.0,25.0,0.0,Mixed or unknown
1236,Central America,"Tue, 10/18/2022 - 12:00",2022,October,3.0,0.0,3,5.0,0.0,3.0,0.0,Vehicle accident / death linked to hazardous t...
1237,Central America,"Wed, 10/19/2022 - 12:00",2022,October,1.0,0.0,1,0.0,0.0,1.0,0.0,Vehicle accident / death linked to hazardous t...
1238,Northern Africa,"Wed, 10/12/2022 - 12:00",2022,October,0.0,22.0,22,30.0,0.0,0.0,0.0,Drowning
1239,Mediterranean,"Thu, 10/13/2022 - 12:00",2022,October,2.0,5.0,7,8.0,0.0,0.0,2.0,Drowning

The data type of date is currently object, so Pandas does not know that this column is a date. We can convert it into a datetime column using the pd.to_datetime method.

You can see that it now has the datatype datetime64. We can now extract different parts of the data into separate columns, using the DatetimeIndex class

## **Writing data back to files**

After completing your data sorting, cleaning, transformnation and adding new columns, you should write the results back to a file. Let us first create a data frame containing just the columns we wish to record.

In [17]:
immigrant_df.to_csv('missing_immigrant.csv', index=None)